version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - DB_URL=postgres://admin:123@db:5432/rinha
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "45MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

  db:
    image: postgres:alpine
    hostname: db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: rinha
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.config_file
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.config_file
    deploy: 
      resources:
        limits:
          cpus: "0.55"
          memory: "420MB"

networks:
  default:
    driver: bridge
    name: rinha-backend